matrix:
  include:
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode9

language: objective-c

before_install:
  - brew update
  - brew install carthage

script:
  - xcodebuild build test -scheme log4swift-OSX
  - carthage build --no-skip-current

branches:
  only:
    - master
